import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

import { prioritizeRuntimeBinPathEntries } from '../src/electron-app.mjs'

const electronAppSource = () => readFile(new URL('../src/electron-app.mjs', import.meta.url), 'utf8')
const extensionHtmlSource = () => readFile(new URL('../src/ui/extensions.html', import.meta.url), 'utf8')

test('Desktop runtime-bin remains first ahead of managed Git and duplicate Windows spellings', () => {
  assert.deepEqual(prioritizeRuntimeBinPathEntries(
    'C:\\Desktop\\runtime-bin',
    ['C:\\Desktop\\managed-git\\cmd', 'c:\\desktop\\RUNTIME-BIN', 'C:\\Windows\\System32'],
    { platform: 'win32' },
  ), [
    'C:\\Desktop\\runtime-bin',
    'C:\\Desktop\\managed-git\\cmd',
    'C:\\Windows\\System32',
  ])
})

test('Extension Dock defaults new external plugin installs to the persistent full-access primary Runtime', async () => {
  const source = await extensionHtmlSource()
  assert.match(source, /name="fullAccess" checked/u)
  assert.match(source, /主 Runtime 完整权限（默认）/u)
  assert.match(source, /持久化 Desktop Profile/u)
})

test('Electron wires full-access plugin approval through the main-process session permission store', async () => {
  const source = await electronAppSource()
  const permissionStoreAt = source.indexOf('let freeModePermissionStore')
  const initializationAt = source.indexOf('const fullAccessApprovalUnavailable = async () =>')
  const registrationAt = source.indexOf('const unregisterExtensionIpc = registerExtensionIpc({', initializationAt)

  assert.match(source, /assertExternalPluginDescriptor,[\s\S]*ExternalPluginSourceResolver,[\s\S]*stageExternalPluginSource,[\s\S]*from '\.\/external-plugin-source\.mjs'/u)
  assert.match(source, /import \{ createFreeModePluginApproval \} from '\.\/free-mode-plugin-approval\.mjs'/u)
  assert.match(source, /import \{ FreeModePermissionStore, freeModePermissionSourceFromDescriptor \} from '\.\/free-mode-permission-store\.mjs'/u)
  assert.ok(permissionStoreAt >= 0)
  assert.ok(initializationAt >= 0)
  assert.ok(registrationAt > initializationAt)

  const permissionStoreInitialization = source.slice(permissionStoreAt, initializationAt)
  assert.match(permissionStoreInitialization, /path: join\(userData, 'free-mode-permissions\.json'\)/u)
  assert.match(permissionStoreInitialization, /await freeModePermissionStore\.load\(\)/u)

  const initialization = source.slice(initializationAt, registrationAt)
  assert.match(initialization, /const permissionStore = await resolveFreeModeSessionPermissionStore\(\)/u)
  assert.match(initialization, /const forceOnce = permissionStore === emergencyFreeModePermissionStore/u)
  assert.match(initialization, /new ExternalPluginSourceResolver\(\{ baseDir: desktopProfileDir \}\)/u)
  assert.match(initialization, /permissionStore,/u)
  assert.match(initialization, /forceOnce,/u)
  assert.match(initialization, /getWindow: \(\) => extensionWindow \?\? startupRecoveryShell\?\.window \?\? mainWindow/u)
  assert.match(initialization, /const approval = await getFullAccessPluginApproval\(\)/u)

  const registration = source.slice(registrationAt, registrationAt + 1_200)
  assert.match(registration, /resolveFullAccessPlugin,/u)
  assert.match(registration, /confirmFullAccessPlugin,/u)
  assert.match(registration, /revalidateFullAccessPlugin,/u)
  assert.match(registration, /completeFullAccessPlugin,/u)
})

test('Electron confines a damaged durable permission ledger to freshly confirmed once-only plugin sessions', async () => {
  const source = await electronAppSource()
  const initializationAt = source.indexOf('const fullAccessApprovalUnavailable = async () =>')
  const registrationAt = source.indexOf('const unregisterExtensionIpc = registerExtensionIpc({', initializationAt)
  const initialization = source.slice(initializationAt, registrationAt)

  assert.match(source, /const resolveFreeModeSessionPermissionStore = async \(\) =>/u)
  assert.match(source, /freeModePermissionStore = undefined/u)
  assert.match(source, /emergencyFreeModePermissionStore = new FreeModePermissionStore/u)
  assert.match(source, /path: join\(userData, `free-mode-session-permissions-\$\{process\.pid\}\.json`\)/u)
  assert.match(initialization, /const forceOnce = permissionStore === emergencyFreeModePermissionStore/u)
  assert.match(initialization, /forceOnce,/u)
  assert.match(initialization, /fullAccessPluginApprovalStore !== permissionStore/u)
  assert.match(initialization, /full-access plugin approval unavailable: \$\{error instanceof Error \? error\.name : 'unknown'\}/u)
})

test('Electron uses one persistent full-user primary Runtime and keeps isolated Runtime creation behind recovery actions', async () => {
  const source = await electronAppSource()
  const isolatedFreeModeAt = source.indexOf('const launchIsolatedFullUserFreeMode = async')
  const freeModeAt = source.indexOf('const enterFullUserFreeMode = async () =>')
  const admissionAt = source.indexOf('const prepareFreeModeRuntimeAdmission = async () =>')
  const controllerFactoryAt = source.indexOf('createRuntimeController: async', isolatedFreeModeAt)
  const preflightAt = source.indexOf('const preflightMigration = await preflightDesktopMigrationGate')
  const primaryRuntimeEvidenceAt = source.indexOf('runtimeFileHashes = await verifyRuntimeFileEvidence', preflightAt)
  const runtimeUnavailableAt = source.indexOf('if (app.isPackaged && runtimeUnavailable)', primaryRuntimeEvidenceAt)
  const primaryPermissionAt = source.indexOf('primaryFullUserPermission = await ensurePrimaryRuntimeFullUserPermission')
  const primaryControllerAt = source.indexOf('const rawRuntimeController = new DshRuntimeController({')
  const shutdownAt = source.indexOf('const shutdownLifecycle = createDesktopShutdownLifecycle')

  assert.match(source, /import \{ createFreeModeLauncher \} from '\.\/free-mode-launcher\.mjs'/u)
  assert.match(source, /writeIsolatedRecoveryFullUserOverlay,[\s\S]*writePrimaryFullUserOverlay,[\s\S]*from '\.\/free-mode-full-user-overlay\.mjs'/u)
  assert.match(source, /import \{ ensurePrimaryRuntimeFullUserPermission \} from '\.\/primary-runtime-permission\.mjs'/u)
  assert.match(source, /import \{ FreeModeRuntimeService \} from '\.\/free-mode-runtime-service\.mjs'/u)
  assert.match(source, /import \{ FreeModeSessionManager \} from '\.\/free-mode-session\.mjs'/u)
  assert.ok(isolatedFreeModeAt >= 0)
  assert.ok(freeModeAt > isolatedFreeModeAt)
  assert.ok(admissionAt >= 0)
  assert.ok(controllerFactoryAt > isolatedFreeModeAt)
  assert.ok(freeModeAt < preflightAt)
  assert.ok(primaryRuntimeEvidenceAt > preflightAt)
  assert.ok(runtimeUnavailableAt > primaryRuntimeEvidenceAt)
  assert.ok(primaryPermissionAt > runtimeUnavailableAt)
  assert.ok(primaryPermissionAt > preflightAt)
  assert.ok(primaryControllerAt > primaryPermissionAt)
  assert.ok(shutdownAt > freeModeAt)

  const isolatedFreeMode = source.slice(isolatedFreeModeAt, freeModeAt)
  const freeModeEntrypoint = source.slice(freeModeAt, preflightAt)
  assert.match(isolatedFreeMode, /originalDshHome: dshHome/u)
  assert.match(isolatedFreeMode, /profileName,/u)
  assert.match(isolatedFreeMode, /backgroundAutomation: true/u)
  assert.match(isolatedFreeMode, /migrationWorker: false/u)
  assert.match(isolatedFreeMode, /fullUser: true/u)
  assert.match(source, /DSH_PERMISSION_MODE: fullUser \? 'danger-full-access' : 'workspace-write'/u)
  assert.match(source, /a migration worker cannot run with full-user permissions/u)
  assert.match(isolatedFreeMode, /writeIsolatedRecoveryFullUserOverlay\(\{ userData \}\)/u)
  assert.match(isolatedFreeMode, /patchFiles: \[fullUserOverlay\]/u)
  assert.match(isolatedFreeMode, /verifyRuntimeFileEvidence/u)
  assert.match(isolatedFreeMode, /assertRuntimeIntegrity/u)
  assert.doesNotMatch(source.slice(admissionAt, isolatedFreeModeAt), /free-mode-runtime-bin/u)
  assert.match(isolatedFreeMode, /getSource: async \(\) => source/u)
  assert.match(isolatedFreeMode, /rememberApproval: rememberSourceApproval && permissionStore !== emergencyFreeModePermissionStore/u)
  assert.match(source, /const freeModeWorkbenchSeed = 'desktop-free-workbench-v1'/u)
  assert.doesNotMatch(source, /freeModeWorkbenchSeed = `desktop-free-workbench-v1:\$\{desktopVersion\}`/u)
  assert.match(freeModeEntrypoint, /source: freeModeWorkbenchSource/u)
  assert.match(freeModeEntrypoint, /rememberSourceApproval: true/u)
  assert.match(isolatedFreeMode, /createFreeModeLauncher/u)
  assert.match(isolatedFreeMode, /beforeRuntimeLaunch: async \(\) => \{[\s\S]*await runtimeProvider\.stop\(\)[\s\S]*primary Runtime did not stop before isolated recovery launch/u)
  assert.doesNotMatch(isolatedFreeMode, /ipcMain|ipcRenderer|desktop:action|preload-main/u)

  const primaryRuntime = source.slice(primaryPermissionAt, shutdownAt)
  assert.match(primaryRuntime, /primaryFullUserOverlay = await writePrimaryFullUserOverlay\(\{ userData \}\)/u)
  assert.match(primaryRuntime, /dshHome,/u)
  assert.match(primaryRuntime, /profileName: 'desktop'/u)
  assert.match(primaryRuntime, /patchFilesProvider: \(\) => migrationRuntimeWorker \? \[\] : \[primaryFullUserOverlay\]/u)
  assert.match(source, /const desktopRuntimeEnvironment = \(\) => desktopRuntimeEnvironmentFor\(\{[\s\S]*fullUser: !migrationRuntimeWorker/u)
  assert.match(primaryRuntime, /const startup = beginDesktopStartup\(\{[\s\S]*startRuntime: \(\) => runtimeProvider\.start\(\)/u)
  assert.doesNotMatch(source, /free-mode-runtime-bin/u)
  assert.equal(source.match(/new FreeModeSessionManager\(/gu)?.length, 1)
  assert.equal(source.match(/new DshRuntimeController\(/gu)?.length, 2)
  assert.equal(source.match(/const launched = await enterFullUserFreeMode\(/gu)?.length ?? 0, 0)

  const preflightBranch = source.slice(preflightAt, source.indexOf('const baselineQuarantine =', preflightAt))
  assert.match(preflightBranch, /enterFreeMode: enterFullUserFreeMode/u)
  assert.match(preflightBranch, /chooseExternalPlugin: chooseLocalExternalPluginForFreeMode/u)
  assert.match(preflightBranch, /loadExternalPluginSource: loadExternalPluginSourceForFreeMode/u)
  const profileFailureAt = source.indexOf("category: 'profile-loader-failure'", preflightAt)
  assert.ok(profileFailureAt > preflightAt)
  assert.match(source.slice(profileFailureAt, profileFailureAt + 500), /enterFreeMode: enterFullUserFreeMode/u)
  assert.match(source.slice(shutdownAt), /\(\) => activeFreeModeLauncher\?\.dispose\(\)/u)
})

test('Recovery Shell remote plugin sources stay main-process parsed and isolated from the normal profile', async () => {
  const source = await electronAppSource()
  const loaderAt = source.indexOf('const loadExternalPluginSourceForFreeMode = async (sourceReference) =>')
  const launcherAt = source.indexOf('const launchAuthorizedFullAccessPlugin = async')
  const preflightAt = source.indexOf('const preflightMigration = await preflightDesktopMigrationGate')

  assert.match(source, /parseRemoteExternalPluginReference,[\s\S]*from '\.\/external-plugin-source\.mjs'/u)
  assert.ok(loaderAt > launcherAt)
  assert.ok(preflightAt > loaderAt)
  const loader = source.slice(loaderAt, source.indexOf('// The first Recovery Shell is intentionally created', loaderAt))
  assert.match(loader, /parseRemoteExternalPluginReference\(sourceReference, \{ includeBare: true \}\)/u)
  assert.match(loader, /\['npm', 'git', 'https'\]\.includes\(parsed\.sourceType\)/u)
  assert.match(loader, /\^git\\\+file:/u)
  assert.match(loader, /approval\.resolve\(\{ spec: parsed\.installSpec \}\)/u)
  assert.match(loader, /approval\.confirm\(descriptor\)/u)
  assert.match(loader, /approval\.revalidate\(descriptor\)/u)
  assert.match(loader, /launchAuthorizedFullAccessPlugin\(installationDescriptor, \{[\s\S]*approvedSessionId: approval\.launchSessionIdFor\(installationDescriptor\)/u)
  assert.match(loader, /approval\.complete\(descriptor\)/u)
  assert.doesNotMatch(loader, /pluginManager\.installFullAccessExternal|runtimeProvider\.stop\(/u)

  const recoveryShell = source.slice(source.indexOf('const showStartupRecoveryShell = async'), loaderAt)
  assert.match(recoveryShell, /invokeStartupLoadExternalPluginSource/u)
  assert.match(recoveryShell, /loadExternalPluginSource: invokeStartupLoadExternalPluginSource/u)
  assert.match(recoveryShell, /startupLoadExternalPluginSource = loadExternalPluginSource/u)

  const openRecoveryShellAt = source.indexOf('const openPreflightRecoveryShell = async')
  assert.ok(openRecoveryShellAt >= 0)
  const openRecoveryShell = source.slice(openRecoveryShellAt, source.indexOf('let startupRecoveryState', openRecoveryShellAt))
  assert.match(openRecoveryShell, /freeModeAvailable: typeof enterFreeMode === 'function'/u)

  const preBootstrapWorkerRecoveryAt = source.indexOf("fingerprintSource: 'pre-bootstrap-migration-incomplete'")
  assert.ok(preBootstrapWorkerRecoveryAt > preflightAt)
  const preBootstrapWorkerRecovery = source.slice(preBootstrapWorkerRecoveryAt, preBootstrapWorkerRecoveryAt + 1_100)
  assert.match(preBootstrapWorkerRecovery, /enterFreeMode: enterFullUserFreeMode/u)
  assert.match(preBootstrapWorkerRecovery, /chooseExternalPlugin: chooseLocalExternalPluginForFreeMode/u)
  assert.match(preBootstrapWorkerRecovery, /loadExternalPluginSource: loadExternalPluginSourceForFreeMode/u)
  assert.match(preBootstrapWorkerRecovery, /cloneExistingProfile: cloneExistingProfileIntoFreeMode/u)
})

test('full-access external plugins install transactionally into the persistent Desktop profile', async () => {
  const source = await electronAppSource()
  const isolatedLaunchAt = source.indexOf('const launchAuthorizedFullAccessPlugin = async')
  const callbackAt = source.indexOf('completeFullAccessPlugin = async (descriptor) =>')
  const registrationAt = source.indexOf('const unregisterExtensionIpc = registerExtensionIpc({', callbackAt)

  assert.ok(isolatedLaunchAt >= 0)
  assert.ok(callbackAt >= 0)
  assert.ok(registrationAt > callbackAt)
  const isolatedLaunch = source.slice(isolatedLaunchAt, source.indexOf('const chooseLocalExternalPluginForFreeMode = async', isolatedLaunchAt))
  const callback = source.slice(callbackAt, registrationAt)
  assert.match(isolatedLaunch, /launchIsolatedFullUserFreeMode/u)
  assert.match(isolatedLaunch, /freeModePermissionSourceFromDescriptor\(external\)/u)
  assert.match(isolatedLaunch, /approvedSessionId,/u)
  assert.match(isolatedLaunch, /profileScope: 'isolated-free-mode'/u)
  assert.match(isolatedLaunch, /stageExternalPluginSource\(external/u)
  assert.match(isolatedLaunch, /isolatedPluginManager\.installFullAccessExternal\(stagedExternal\)/u)
  assert.doesNotMatch(isolatedLaunch, /runtimeProvider\.stop\(/u)
  assert.doesNotMatch(isolatedLaunch, /pluginManager\.installFullAccessExternal\(/u)
  assert.match(callback, /await approval\.complete\(descriptor\)/u)
  assert.match(callback, /await rm\(persistentPluginStagingDirectory\(descriptor\), \{ recursive: true, force: true \}\)/u)
  assert.match(source, /const userPluginArchive = new UserPluginArchive\(\{[\s\S]*profileDir: desktopProfileDir/u)
  assert.match(source, /profileArchive: userPluginArchive/u)
  assert.match(source, /pluginManager,[\s\S]*controller: runtimeProvider,[\s\S]*completeFullAccessPlugin,/u)
})

test('Recovery Shell can copy the existing user profile into Free Mode without pointing Runtime at the original path', async () => {
  const source = await electronAppSource()
  const cloneAt = source.indexOf('const cloneExistingProfileIntoFreeMode = async () =>')
  const externalApprovalAt = source.indexOf('const fullAccessApprovalUnavailable = async () =>', cloneAt)

  assert.match(source, /cloneFreeModeAgentConfig,[\s\S]*cloneFreeModeHomePatch,[\s\S]*cloneFreeModeProfile,[\s\S]*inspectFreeModeAgentConfigClone,[\s\S]*inspectFreeModeHomePatch,[\s\S]*inspectFreeModeProfileClone,[\s\S]*from '\.\/free-mode-profile-clone\.mjs'/u)
  assert.ok(cloneAt >= 0)
  assert.ok(externalApprovalAt > cloneAt)
  const clone = source.slice(cloneAt, externalApprovalAt)
  assert.match(clone, /inspectFreeModeProfileClone\(\{ sourceProfileDir: desktopProfileDir \}\)/u)
  assert.match(clone, /inspectFreeModeHomePatch\(\{ sourceDshHome: dshHome \}\)/u)
  assert.match(clone, /inspectFreeModeAgentConfigClone\(\{ sourceDshHome: dshHome \}\)/u)
  assert.match(clone, /agentConfigReview\.digest/u)
  assert.match(clone, /关闭后自动清理的隔离会话/u)
  assert.match(clone, /defaultId: 1/u)
  assert.match(clone, /cancelId: 1/u)
  assert.match(clone, /launchIsolatedFullUserFreeMode/u)
  assert.match(clone, /cloneFreeModeProfile\(\{/u)
  assert.match(clone, /sourceProfileDir: desktopProfileDir/u)
  assert.match(clone, /targetProfileDir: join\(isolatedDshHome, 'profiles', profileName\)/u)
  assert.match(clone, /expectedDigest: review\.digest/u)
  assert.match(clone, /cloneFreeModeHomePatch\(\{/u)
  assert.match(clone, /sourceDshHome: dshHome/u)
  assert.match(clone, /targetDshHome: isolatedDshHome/u)
  assert.match(clone, /expectedDigest: homePatchReview\.digest/u)
  assert.match(clone, /cloneFreeModeAgentConfig\(\{/u)
  assert.match(clone, /expectedDigest: agentConfigReview\.digest/u)
  assert.doesNotMatch(clone, /profileName: 'desktop'|dshHome: dshHome/u)

  const preflightAt = source.indexOf('const preflightMigration = await preflightDesktopMigrationGate')
  const preflightBranch = source.slice(preflightAt, source.indexOf('const baselineQuarantine =', preflightAt))
  assert.match(preflightBranch, /cloneExistingProfile: cloneExistingProfileIntoFreeMode/u)
})

test('Electron puts the stable Desktop runtime-bin first for Runtime, terminal, and plugin child processes', async () => {
  const source = await electronAppSource()
  const confirmationAt = source.indexOf('const confirmManagedGitInstall = async () =>')
  const serviceAt = source.indexOf('const managedGitRuntimeService = createManagedGitRuntimeService({')
  const externalPluginGitAt = source.indexOf('const resolveManagedGitExternalPluginPathEntries = async')
  const initialShellAt = source.indexOf('await showStartupRecoveryShell()')
  const freeModeAt = source.indexOf('const launchIsolatedFullUserFreeMode = async')
  const normalControllerAt = source.indexOf('const rawRuntimeController = new DshRuntimeController({')
  const repairAt = source.indexOf('const installManagedGitForRecovery = async () =>')
  const crashRecoveryAt = source.indexOf("category === 'external-tool-missing' && process.platform === 'win32'")

  assert.match(source, /import \{ createManagedGitRuntimeService \} from '\.\/managed-git-runtime-service\.mjs'/u)
  assert.ok(confirmationAt >= 0)
  assert.ok(serviceAt >= 0)
  assert.ok(serviceAt > confirmationAt)
  assert.ok(externalPluginGitAt > serviceAt)
  assert.ok(initialShellAt > serviceAt)
  assert.ok(freeModeAt > serviceAt)
  assert.ok(normalControllerAt > freeModeAt)
  assert.ok(repairAt > normalControllerAt)
  assert.ok(crashRecoveryAt > repairAt)

  const confirmation = source.slice(confirmationAt, serviceAt)
  const service = source.slice(serviceAt, freeModeAt)
  assert.match(confirmation, /dialog\.showMessageBox/u)
  assert.match(confirmation, /buttons: \['下载并安装', '取消'\]/u)
  assert.match(confirmation, /defaultId: 1/u)
  assert.match(confirmation, /cancelId: 1/u)
  assert.match(confirmation, /不会修改系统 PATH、注册表/u)
  assert.match(service, /userDataDirectory: userData/u)
  assert.match(service, /bundledGitDirectory: app\.isPackaged \? process\.resourcesPath : undefined/u)
  assert.match(service, /confirm: confirmManagedGitInstall/u)
  assert.match(service, /managedGitRuntimeService\.inspect\(pathEntries\)/u)
  assert.match(service, /result\.source === 'bundled'/u)

  const externalPluginGit = source.slice(externalPluginGitAt, initialShellAt)
  assert.match(externalPluginGit, /assertExternalPluginDescriptor\(descriptor\)/u)
  assert.match(externalPluginGit, /directory: primaryRuntimeBinDirectory/u)
  assert.match(externalPluginGit, /managedGitRuntimeService\.inspect\(\[runtimeBin\]\)/u)
  assert.match(externalPluginGit, /prioritizeRuntimeBinPathEntries\(runtimeBin, inspected\.pathEntries\)/u)
  assert.match(externalPluginGit, /\['bundled', 'managed', 'system'\]\.includes\(inspected\.source\)/u)
  assert.match(externalPluginGit, /managedGitRuntimeService\.repair\(\[runtimeBin\]\)/u)
  assert.match(externalPluginGit, /prioritizeRuntimeBinPathEntries\(runtimeBin, outcome\.pathEntries\)/u)
  assert.match(externalPluginGit, /!\['bundled', 'managed', 'system'\]\.includes\(outcome\.source\)/u)
  assert.match(externalPluginGit, /return Object\.freeze\(\[runtimeBin\]\)/u)
  assert.doesNotMatch(externalPluginGit, /process\.env\.(?:PATH|Path)\s*=/u)
  assert.doesNotMatch(externalPluginGit, /\b(?:setx|reg(?:\.exe)?)\b/iu)

  const freeMode = source.slice(freeModeAt, normalControllerAt)
  assert.match(freeMode, /directory: primaryRuntimeBinDirectory/u)
  assert.match(freeMode, /resolveManagedGitRuntimePathEntries\(\s*\[runtimeBin\],\s*'isolated recovery',/u)
  assert.match(freeMode, /pathEntries: runtimePathEntries/u)
  const isolatedPlugin = source.slice(
    source.indexOf('const launchAuthorizedFullAccessPlugin = async'),
    source.indexOf('const chooseLocalExternalPluginForFreeMode = async'),
  )
  assert.match(isolatedPlugin, /resolveManagedGitExternalPluginPathEntries\(external\)/u)
  assert.match(isolatedPlugin, /profileScope: 'isolated-free-mode',[\s\S]*pathEntries: pluginPathEntries/u)

  const normalRuntime = source.slice(normalControllerAt - 700, repairAt)
  assert.match(source, /const runtimeBin = await ensurePnpmCommandShim\(\{[\s\S]*directory: primaryRuntimeBinDirectory,[\s\S]*const runtimePathEntries = await resolveManagedGitRuntimePathEntries\(\[runtimeBin\], 'primary'\)/u)
  assert.match(normalRuntime, /pathEntries: runtimePathEntries/u)

  const repair = source.slice(repairAt, crashRecoveryAt)
  assert.match(repair, /managedGitRuntimeService\.repair\(\[runtimeBin\]\)/u)
  assert.match(repair, /rawRuntimeController\.pathEntries = prioritizeRuntimeBinPathEntries\(runtimeBin, outcome\.pathEntries\)/u)
  assert.match(repair, /void runtimeProvider\.recover\(\)\.catch/u)
  assert.doesNotMatch(repair, /process\.env\.(?:PATH|Path)\s*=/u)
  assert.doesNotMatch(repair, /\b(?:setx|reg(?:\.exe)?)\b/iu)

  const crashRecovery = source.slice(crashRecoveryAt, crashRecoveryAt + 700)
  assert.match(crashRecovery, /installManagedGit: installManagedGitForRecovery/u)
  const rendererLoadAt = source.indexOf('await mainWindow.loadURL(status.url)')
  assert.ok(rendererLoadAt >= 0)
  assert.match(source.slice(rendererLoadAt, rendererLoadAt + 800), /await dismissStartupRecoveryShell\(\)/u)
})

test('late startup recovery retains the already-installed isolated Free Mode actions without crossing run() scope', async () => {
  const source = await electronAppSource()
  const boundaryAt = source.indexOf('return runStartupAfterRecoveryShell({')
  const fallbackAt = source.indexOf('showRecoveryShell: () => {', boundaryAt)
  const fallbackEnd = source.indexOf('\n    },', fallbackAt)

  assert.ok(boundaryAt >= 0)
  assert.ok(fallbackAt > boundaryAt)
  assert.ok(fallbackEnd > fallbackAt)
  const fallback = source.slice(fallbackAt, fallbackEnd)
  assert.match(fallback, /category: 'unknown'/u)
  assert.match(fallback, /retains its established[\s\S]*Electron-main actions/u)
  assert.match(fallback, /failStartupFreeModeAction\(\)/u)
  assert.doesNotMatch(fallback, /enterFreeMode: enterFullUserFreeMode/u)
  assert.doesNotMatch(fallback, /chooseExternalPlugin: chooseLocalExternalPluginForFreeMode/u)
  assert.doesNotMatch(fallback, /cloneExistingProfile: cloneExistingProfileIntoFreeMode/u)
})
