// Generated by scripts/sync-shared.mjs from shared/client/feature-telemetry.ts. Do not edit this copy; edit the shared source and run "node scripts/sync-shared.mjs".
export type FeatureEvent =
  | { feature: 'project'; outcome: 'started' | 'succeeded' | 'failed'; detail: 'create' | 'connect' }
  | { feature: 'attachment'; outcome: 'started' | 'succeeded' | 'failed' | 'cancelled'; detail: 'file' }

/** Send fixed product signals only. An unavailable bridge must never affect work. */
export function reportFeatureEvent(event: FeatureEvent): void {
  try {
    const bridge = (globalThis as unknown as { dshDesktop?: { recordFeatureEvent?: (event: FeatureEvent) => unknown } }).dshDesktop
    const result = bridge?.recordFeatureEvent?.(event)
    void Promise.resolve(result).catch(() => {})
  } catch { /* Telemetry is best effort. */ }
}
