export const COMMUNITY_QQ_URL = 'https://qm.qq.com/q/vehlNjaeye'
export const GITHUB_DOWNLOADS_URL = 'https://github.com/ningbainb/deepseek-harness-desktop/releases/latest'
export const GITHUB_FEEDBACK_URL = 'https://github.com/ningbainb/deepseek-harness-desktop/issues/new/choose'
export const GITHUB_PROJECT_URL = 'https://github.com/ningbainb/deepseek-harness-desktop'
export const AFDIAN_SPONSOR_URL = 'https://afdian.com/a/ningbai'
export const PRIVACY_POLICY_URL = 'https://ningbainb.github.io/deepseek-harness-desktop/privacy.html'
